# LSQM Sources Configuration
# These sources are used to discover Terraform architectures for testing

# Direct GitHub repositories with standalone Terraform configs
github_repos:
  enabled: true
  repositories:
    # AWS Samples - complete example projects (standalone Terraform)
    - url: https://github.com/aws-samples/serverless-patterns
      paths:
        - "apigw-lambda-dynamodb-terraform"
        - "s3-lambda-terraform"
        - "eventbridge-lambda-terraform"
        - "lambda-destinations-terraform"
        - "apigw-rest-api-lambda-terraform"
        - "apigw-http-api-lambda-terraform"
        - "dynamodb-streams-lambda-terraform"

# Disable other sources that mostly find non-standalone modules
terraform_registry: false
github_orgs: false
serverless: false
cdk: false
