# LSQM Sources Configuration
# These sources are used to discover Terraform architectures for testing

# Direct GitHub repositories with standalone Terraform configs
github_repos:
  enabled: true
  repositories:
    # AWS Serverless Patterns - search for all Terraform examples
    - url: https://github.com/aws-samples/serverless-patterns
      paths:
        - "*-terraform"
        - "**/*-terraform"
    # Terraform Provider AWS examples
    - url: https://github.com/hashicorp/terraform-provider-aws
      paths:
        - "examples"

# GitHub Organizations - scan for .tf files
github_orgs:
  enabled: true
  organizations:
    - aws-samples
    - terraform-aws-modules
  file_patterns:
    - "*.tf"
    - "examples/**/*.tf"
  max_files_per_repo: 100
  skip_archived: true
  skip_forks: true

# Terraform Registry - popular AWS modules
terraform_registry:
  enabled: true
  providers:
    - aws
  limit_per_provider: 100
  min_downloads: 1000

# Disable sources with lower standalone yield
serverless: false
cdk: false
